#!/usr/bin/env python3
"""gen_rootfs.py — генерирует C-файл с данными rootfs."""

import os
import sys

def to_c_array(data):
    """Преобразует байты в C-массив с hex-числами."""
    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        line = ', '.join(f'0x{b:02X}' for b in chunk)
        lines.append('    ' + line + ',')
    return '\n'.join(lines) if lines else '    0x00,'

def main():
    rootfs_dir = "sys/rootfs"
    out_file = "build/rootfs_data.c"

    if not os.path.isdir(rootfs_dir):
        print(f"[ERROR] {rootfs_dir} not found", file=sys.stderr)
        return 1

    os.makedirs("build", exist_ok=True)
    entries = []

    for dirpath, dirnames, filenames in os.walk(rootfs_dir):
        dirnames[:] = [d for d in dirnames if not d.startswith('.')]
        rel_dir = os.path.relpath(dirpath, rootfs_dir)
        if rel_dir == '.':
            rel_dir = ''

        for fname in sorted(filenames):
            if fname.startswith('.'):
                continue
            full_path = os.path.join(dirpath, fname)
            rel_path = os.path.join(rel_dir, fname).replace('\\', '/')

            with open(full_path, 'rb') as f:
                data = f.read()

            entries.append((rel_path, data))

    with open(out_file, 'w') as out:
        out.write('/* Auto-generated by tools/gen_rootfs.py — DO NOT EDIT */\n')
        out.write('#include "rootfs.h"\n\n')

        for i, (path, data) in enumerate(entries):
            out.write(f'/* {path} — {len(data)} bytes */\n')
            out.write(f'static const unsigned char data_{i}[] = {{\n')
            out.write(to_c_array(data))
            out.write('\n};\n\n')

        out.write('const rootfs_entry_t rootfs_entries[] = {\n')
        for i, (path, data) in enumerate(entries):
            out.write(f'    {{"{path}", (const char*)data_{i}, {len(data)}}},\n')
        out.write('};\n\n')
        out.write(f'const int rootfs_count = {len(entries)};\n')

    print(f"[OK] Generated {out_file}")
    for path, data in entries:
        print(f"     {path} ({len(data)} bytes)")
    return 0

if __name__ == '__main__':
    sys.exit(main())