import os

ROOTFS_DIR = os.path.join("sys", "rootfs")
OUTPUT_C = os.path.join("sys", "kernel", "fsdata.c")

def main():
    if not os.path.exists(ROOTFS_DIR):
        os.makedirs(ROOTFS_DIR)

    entries = []

    for root, dirs, files in os.walk(ROOTFS_DIR):
        for d in dirs:
            full_path = os.path.join(root, d)
            rel_path = "/" + os.path.relpath(full_path, ROOTFS_DIR).replace("\\", "/")
            entries.append({'type': 'DIR', 'path': rel_path, 'data': b''})

        for f in files:
            full_path = os.path.join(root, f)
            rel_path = "/" + os.path.relpath(full_path, ROOTFS_DIR).replace("\\", "/")
            with open(full_path, "rb") as fp:
                data = fp.read()
            entries.append({'type': 'FILE', 'path': rel_path, 'data': data})

    with open(OUTPUT_C, "w", encoding="utf-8") as out:
        out.write("// Auto-generated by make_fsdata.py\n")
        out.write('#include "fs.h"\n\n')
        out.write("typedef struct {\n")
        out.write("    const char *path;\n")
        out.write("    int is_dir;\n")
        out.write("    const char *data;\n")
        out.write("    int size;\n")
        out.write("} init_fs_entry_t;\n\n")

        out.write("const init_fs_entry_t builtin_fs[] = {\n")
        for e in entries:
            is_dir = 1 if e['type'] == 'DIR' else 0
            bytes_str = "".join([f"\\x{b:02x}" for b in e['data']])
            out.write(f'    {{ "{e["path"]}", {is_dir}, "{bytes_str}", {len(e["data"])} }},\n')
        
        out.write("    { 0, 0, 0, 0 }\n")
        out.write("};\n")

if __name__ == "__main__":
    main()